### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by Poucous** [Poucous/smartReader#2]
### By priority:
- [ ] Solve the problem with css when the span tag is append, maybe deleting it.

- [ ] End toolbar:
 - **Search a way to execute a "content_script" from the "background".** To launch the main script when the addon is activated. 
 - Give a class to each <b> added that we can remove, when the addon is disabled.

- [ ] Split functions in files for readability.

- [ ] Add a popup or a page to configure the extension (filter for sites, disable only social medias).

Notes : 
[https://thewebdev.info/2021/06/03/how-to-remove-only-the-parent-element-and-not-its-child-elements-in-javascript] (delete span without b)

**Comment by astro-zilla** [comment]
Would be helpful to add a keyboard shortcut for enabling/disabling, along with the aforementioned config options

**Comment by Poucous** [comment]
Hello, it's a good idea, I'll see how it goes to put it in the menu

**Comment by user8446** [comment]
Hi,

I came here to open a feature request to only effect the focused tab and not all tabs and saw "Disable sites, put them in a blacklist like uBlock" on the to-do list which would work as well.

Great to see it already there!

Thank you

**Comment by Poucous** [comment]
Hello,

Yep, it's the idea when I would implement the blacklist like uBlock, it should improve performance at the same time

**Comment by user8446** [comment]
Hi, in addition to the blacklist would you consider only effect the focused tab? The reason is because smartReader does not work on every site (it sometime corrupts it where it has to be turned off and then refreshed - I just noticed this on Google Calendar). It would be impractical to add sites daily to the blacklist.

**Comment by Poucous** [comment]
The blacklist will be done per site, and the effect will be taken on active windows (dynamically)

**Comment by szczekulskij** [comment]
Hi @Poucous - any update on "Add a popup or a page to configure the extension" ?

I'm happy to pick this up and help out : )
Would need a quick walkthrough repo tho, can you PM me so we can discuss?
